### ISSUE TITLE
Hide some fields from normal users

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#141]
Some fields should not be serialised unless the current user is an admin or it's information about oneself. These fields are:
* User#email
* User#unconfirmed_email

(add more items to this list)

**Comment by phyrog** [comment]
Here are some pointers for implementing this:

- http://graphql-ruby.org/pro/authorization.html (Authorization in the PRO version of `graphql-ruby`
- https://github.com/phyrog/graphql-pundit (My attempt at implementing something similar with focus on Pundit; missing some features we want/need)
- https://github.com/exAspArk/graphql-guard (Found that today, can be integrated with Pundit, however seems to be more verbose than my attempt)

**Comment by phyrog** [comment]
What I would expect from the lib:

- `authorize :email` should be enough to check the `email?` permission on the parent object, so that simple things stay simple
- `authorize :create, User`: Using different policies should be supported in an easy way
- `authorize ->(root, args, ctx) {}`: Custom authorization logic (e.g. to call policy methods with arguments) can be supported in a general way
- Some sort of Pundit scopes support

The first two are supported by `graphql-pundit`, the third seems to be the only option for `graphql-guard`

**Comment by phyrog** [comment]
Closes in favor of #175.
