### ISSUE TITLE
Don't leak existence of a private repository

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub-backend#277]
Consider the query
```graphql
query( $id: !ID) {
  repository(id: $id) {
    name
  }
}
```

Setting the `$id` to `"the-league-of-extraordinary-users/top-secret"` while signed in as ada, the result is:
```
{
  "data": {
    "repository": {
      "name": "Top Secret"
    }
  }
}
```
which is just fine. However, when not signed in, the result is:
```
{
  "data": {
    "repository": null
  }
}
```
It looks like the message that we want to have when a repository doesn't exist, but it isn't. When setting the `$id` to `"i-dont-exist"`, the result is
```
{
  "data": {
    "repository": null
  },
  "errors": [
    {
      "message": "resource not found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "repository"
      ]
    }
  ]
}
```

The last two results must be the same if we don't want to leak the existence of a private repository.

**Comment by phyrog** [comment]
I think the first one is preferable. This case can be fixed easily by changing the `ResourceInstrumenter` a bit, but unfortunately that breaks other tests.

The problem is that we (1) sometimes want to return `null` without an error, (2) sometimes return `null` and an error and (3) sometimes just call the next instrumenter (authorization) regardless of whether the resource is `nil`. We currently only support the second and third options via `resource!` and `resource`, while the fix would only support the first and second option.

The third case is currently used by mutations concerning the `current_user` (delete/save account, add/remove public key), to return the appropriate "not authorized" error instead of "resource not found". If we can find a way to change these, we can apply the above mentioned easy fix.
