### ISSUE TITLE
Simplify Rubocop config

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-backend#379]
I'm just wondering why we have the complete rubocop configs in each repo. Since we regularly update these to include new standards, why not have a config file with only our changes? According to the rubocop docs: "Project and personal .rubocop.yml files need only make settings that are different from the default ones."

Even better, we could upload the config in one repo only and do this in all other repos:

```yaml
inherit_from:
  - https://raw.githubusercontent.com/ontohub/ontohub-backend/master/.rubocop.yml
```

But I realize that might be problematic due to rubocop's config changes with each new version. Still, we could probably make the configs a lot smaller.

**Comment by phyrog** [comment]
Also: https://github.com/pocke/mry

**Comment by eugenk** [comment]
Ah ok, it seems reasonable to only have what's modified in the`.rubocop.yml`.

I would not inherit from a web resource because we would not be able to run rubocop locally when we are offline.

I had a look at mry a few months ago and they seem _not_ to be up to date even after a few weeks since a new rubocop version.

**Comment by phyrog** [comment]
Regarding mry: yeah, I noticed that too. No support for version 0.52 yet
