### ISSUE TITLE
Provide `readme` field on commit

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub-backend#418]
Like GitHub, we should support multiple readme formats (or at least readme file names). The `readme` field should return a `File`. The returned file should be the first file found matching `readme`, `readme.md`, `readme.markdown`, `readme.txt`, etc. (case-insensitive).

The goal is to be able to do a query like this:

```graphql

repository(id: ...) {
  commit(revision: ...) {
    readme {
      content
    }
  }
}
```

**Comment by eugenk** [comment]
What's the intention of this code? Naively speaking, I would think that the frontend just asks if there is a readme.{md,markdown,txt} in the current directory and then displays it. At least I suspect that Github does this. This issue is clearly something different because the backend provides a single readme file per repository (not per directory).

**Comment by phyrog** [comment]
The frontend would need to ask for multiple file formats, uppercase, lowercase etc. So instead of trial-and-error from the frontend, we can just provide the first readme file from the backend.

But you're right, we could add a path argument so that you can ask for a readme file in another directory.

**Comment by eugenk** [comment]
I don't think that the backend should decide what the frontend can display beautifully. The frontend should be able to query for all files in a specific directory (it can do this with the `repository.commit.directory` query) and find an appropriate file. Since this is only for presentation to the end user, this is the job of the frontend.

**Comment by eugenk** [comment]
> Using lsFiles would need another request to fetch the actual file.

Sure, but that's not a big issue. If this was a REST interface, the frontend would need to send much more than just two requests. Still, I don't think that the backend is responsible in this case.
